# Generated by Django 4.1.13 on 2024-05-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviewrating_productgallery'),
        ('carts', '0002_cartsitem_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartsItem',
            new_name='CartItem',
        ),
    ]
